#!/usr/bin/env python3
# File: generate_ultrahuman_pdf_report.py
# Description: Fetches last 7 days via Ultrahuman API, builds diagrams, outputs one PDF report.
# Created: 2026-03-15
# Last updated: 2026-03-15

"""
Run from repo root with .env set:
  cd ultrahuman-mcp && source .env 2>/dev/null; .venv/bin/python scripts/generate_ultrahuman_pdf_report.py
Output: reports/ultrahuman_report_YYYY-MM-DD.pdf
"""

from __future__ import annotations

import os
import sys
from datetime import datetime, timedelta
from pathlib import Path

# Repo root and .env
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
_env = ROOT / ".env"
if _env.exists():
    for line in _env.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, _, v = line.partition("=")
            os.environ.setdefault(k.strip(), v.strip())

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
import numpy as np

from ultrahuman_mcp.client import fetch_daily_metrics


def _extract_day(data: dict) -> dict:
    """Extract sleep, recovery, hrv, steps from one day's API response."""
    out = {"sleep": None, "recovery": None, "hrv": None, "steps": None}
    inner = data.get("data") or {}
    for m in (inner.get("metric_data") or []):
        t = m.get("type")
        obj = m.get("object") or {}
        if t == "sleep":
            out["sleep"] = obj.get("score")
        elif t == "recovery":
            out["recovery"] = obj.get("score")
        elif t == "hrv":
            out["hrv"] = obj.get("avg")
        elif t == "steps":
            avg = obj.get("avg")
            out["steps"] = int(round(avg)) if avg is not None else None
    return out


def main() -> int:
    email = os.getenv("ULTRAHUMAN_EMAIL", "").strip()
    if not email:
        print("Set ULTRAHUMAN_EMAIL in .env", file=sys.stderr)
        return 1

    # Fetch last 7 days
    dates = [(datetime.now() - timedelta(days=i)).strftime("%Y-%m-%d") for i in range(1, 8)]
    rows = []
    for i, d in enumerate(dates):
        print(f"[{i+1}/7] Fetching {d}...", flush=True)
        try:
            data = fetch_daily_metrics(email, d)
            rows.append((d, _extract_day(data)))
        except Exception as e:
            print(f"  Warning: {e}", file=sys.stderr)
            rows.append((d, {"sleep": None, "recovery": None, "hrv": None, "steps": None}))

    dates_str = [r[0] for r in rows]
    sleep = [r[1]["sleep"] for r in rows]
    recovery = [r[1]["recovery"] for r in rows]
    hrv = [r[1]["hrv"] for r in rows]
    steps = [r[1]["steps"] for r in rows]

    # Short labels for x-axis (e.g. Mon 10)
    labels = []
    for d in dates_str:
        try:
            dt = datetime.strptime(d, "%Y-%m-%d")
            labels.append(dt.strftime("%a %d"))
        except Exception:
            labels.append(d)

    out_dir = ROOT / "reports"
    out_dir.mkdir(exist_ok=True)
    pdf_path = out_dir / f"ultrahuman_report_{datetime.now().strftime('%Y-%m-%d')}.pdf"

    with PdfPages(pdf_path) as pdf:
        # Page 1: Title + summary
        fig, ax = plt.subplots(figsize=(8, 10))
        fig.suptitle("Ultrahuman Weekly Report", fontsize=16, fontweight="bold")
        ax.axis("off")
        avg_sleep = np.nanmean([s for s in sleep if s is not None]) if any(s is not None for s in sleep) else None
        avg_rec = np.nanmean([r for r in recovery if r is not None]) if any(r is not None for r in recovery) else None
        avg_hrv = np.nanmean([h for h in hrv if h is not None]) if any(h is not None for h in hrv) else None
        total_steps = sum(s for s in steps if s is not None)
        sleep_txt = f"{avg_sleep:.1f}/10" if avg_sleep is not None else "—"
        rec_txt = f"{avg_rec:.1f}/10" if avg_rec is not None else "—"
        hrv_txt = f"{avg_hrv:.1f}" if avg_hrv is not None else "—"
        text = f"""
Report period: {dates_str[-1]} to {dates_str[0]} (last 7 days)

Summary:
• Average Sleep Score: {sleep_txt}
• Average Recovery Score: {rec_txt}
• Average HRV: {hrv_txt}
• Total Steps: {total_steps}

Generated by Ultrahuman MCP · Authors: duzzafizzl & Mioré (AI)
"""
        ax.text(0.1, 0.5, text.strip(), transform=ax.transAxes, fontsize=11, verticalalignment="center", family="sans-serif")
        pdf.savefig(fig, bbox_inches="tight")
        plt.close(fig)

        # Page 2: Sleep & Recovery over days (line chart)
        fig, ax = plt.subplots(figsize=(10, 5))
        x = np.arange(len(dates_str))
        if any(s is not None for s in sleep):
            ax.plot(x, [s if s is not None else np.nan for s in sleep], marker="o", label="Sleep Score", color="C0")
        if any(r is not None for r in recovery):
            ax.plot(x, [r if r is not None else np.nan for r in recovery], marker="s", label="Recovery Score", color="C1")
        ax.set_xticks(x)
        ax.set_xticklabels(labels, rotation=45, ha="right")
        ax.set_ylabel("Score (0–10)")
        ax.set_title("Sleep & Recovery (last 7 days)")
        if ax.get_legend_handles_labels()[0]:
            ax.legend(loc="best")
        ax.set_ylim(0, 10.5)
        ax.grid(True, alpha=0.3)
        pdf.savefig(fig, bbox_inches="tight")
        plt.close(fig)

        # Page 3: Steps (bar chart)
        fig, ax = plt.subplots(figsize=(10, 5))
        steps_plot = [s if s is not None else 0 for s in steps]
        colors = plt.cm.viridis(np.linspace(0.2, 0.8, len(steps_plot)))
        bars = ax.bar(x, steps_plot, color=colors, edgecolor="gray", linewidth=0.5)
        ax.set_xticks(x)
        ax.set_xticklabels(labels, rotation=45, ha="right")
        ax.set_ylabel("Steps")
        ax.set_title("Daily Steps (last 7 days)")
        ax.grid(True, alpha=0.3, axis="y")
        pdf.savefig(fig, bbox_inches="tight")
        plt.close(fig)

        # Page 4: HRV trend (line)
        if any(h is not None for h in hrv):
            fig, ax = plt.subplots(figsize=(10, 5))
            ax.plot(x, [h if h is not None else np.nan for h in hrv], marker="o", color="green", linewidth=2, markersize=8)
            ax.set_xticks(x)
            ax.set_xticklabels(labels, rotation=45, ha="right")
            ax.set_ylabel("HRV (avg)")
            ax.set_title("HRV Trend (last 7 days)")
            ax.grid(True, alpha=0.3)
            pdf.savefig(fig, bbox_inches="tight")
            plt.close(fig)

    print(f"PDF saved: {pdf_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
